[settings]
branch = "{SPACE}-{UNIQUE}"

[repositories.spaces]
git = "https://github.com/work-spaces/spaces"
checkout = "Revision"
rev = "1a4f517113c54d1bdd73a21076ef77962a5c5f5e"

[actions]

local_archive = [
    { name = "build", command = "cargo", working_directory = "spaces", arguments = [
        "build",
        "--profile=release",
    ] },
    { name = "mkdir", command = "mkdir", arguments = [
        "-p",
        "deploy",
    ] },
    { name = "archive", command = "spaces", arguments = [
        "create-binary-archive",
        "--name=spaces",
        "--version={SPACES_TOML:spaces/Cargo.toml/package.version}",
        "--output=deploy",
        "--input=spaces/target/release/spaces",
    ] }
]


deploy = [
    { name = "build", command = "cargo", working_directory = "spaces", arguments = [
        "build",
        "--profile=release",
    ] },
    { name = "mkdir", command = "mkdir", arguments = [
        "-p",
        "deploy",
    ] },
    { name = "archive", command = "spaces", arguments = [
        "create-binary-archive",
        "--name=spaces",
        "--version={SPACES_TOML:spaces/Cargo.toml/package.version}",
        "--output=deploy",
        "--input=spaces/target/release/spaces",
    ] },
    { name = "check_release", command = "gh", working_directory = "spaces", arguments = [
        "release",
        "view",
        "spaces-v{SPACES_TOML:spaces/Cargo.toml/package.version}",
        "--repo=https://github.com/work-spaces/workflows"
    ] },
    { name = "upload", command = "gh", working_directory = "spaces", arguments = [
        "release",
        "upload",
        "spaces-v{SPACES_TOML:spaces/Cargo.toml/package.version}",
        "../deploy/spaces-v{SPACES_TOML:spaces/Cargo.toml/package.version}-{SPACES_PLATFORM}.zip",
        "--repo=https://github.com/work-spaces/workflows"
    ] },
]

release = [
    { name = "release", command = "gh", working_directory = "spaces", arguments = [
        "release",
        "create",
        "spaces-v{SPACES_TOML:spaces/Cargo.toml/package.version}",
        "--generate-notes",
        "--repo=https://github.com/work-spaces/workflows"
    ] },
]