# Workflow shortcuts
#
# For example: spaces checkout --workflow=workflows:llvm-build-16 --name=llvm-build-test

llvm-build-16 = ["lock", "preload", "llvm16-config", "llvm-build"]
llvm-build-17 = ["lock", "preload", "llvm17-config", "llvm-build"]
llvm-build-18 = ["lock", "preload", "llvm18-config", "llvm-build"]
packages-test = ["lock", "preload", "packages-test"]
packages-test-dev = ["preload", "packages-test"]
packages-update = ["preload", "packages-update"]
capsules-build = ["lock", "preload", "preload-sources", "capsules-build"]
capsules-build-dev = ["preload", "preload-sources", "capsules-build"]
git-build = ["preload", "preload-sources", "git-build"]
node-sdk = ["lock", "preload", "node-sdk"]
llvm-sdk = ["lock", "preload", "llvm-sdk"]
python-sdk = ["lock", "preload", "python-sdk"]
go-sdk = ["lock", "preload", "go-sdk"]
conan-sdk = ["lock", "preload", "conan-sdk"]
ninja-build = ["lock", "preload", "ninja-build"]
curl-build = ["lock", "preload", "curl-build"]
kill-demo = ["lock", "preload", "kill-demo"]
ruby-sdk = ["lock", "preload", "ruby-sdk"]
qemu-arm-build = ["lock", "preload", "qemu-arm-build"]
shell-test = ["lock", "preload", "shell-test"]
workflows-test = ["preload", "workflows-test"]
target-test = ["lock", "preload", "target-test"]
target-test-dev = ["preload", "target-test"]
sparse-checkout-test = ["lock", "preload", "sparse-checkout-test"]
spaces-dev = ["preload", "spaces-develop"]
spaces-docs = ["lock", "preload", "spaces-docs"]
serve-rules = ["preload", "preload-sources", "serve-rules", "capsules-build"]
doxygen-build = ["lock", "preload", "doxygen-build"]

[ninja-build-dev]
checkout_scripts = ["preload", "ninja-build"]
new_branches = ["//ninja-build:ninja-build"]
