# Workflow shortcuts
#
# For example: spaces checkout --workflow=workflows:llvm-build-16 --name=llvm-build-test

llvm-build-16 = ["lock", "preload", "llvm16-config", "llvm-build"]
llvm-build-17 = ["lock", "preload", "llvm17-config", "llvm-build"]
llvm-build-18 = ["lock", "preload", "llvm18-config", "llvm-build"]
packages-test = ["lock", "preload", "packages-test"]
git-build = ["lock", "preload", "git-build"]
node-sdk = ["lock", "preload", "node-sdk"]
llvm-sdk = ["lock", "preload", "llvm-sdk"]
python-sdk = ["lock", "preload", "python-sdk"]
go-sdk = ["lock", "preload", "go-sdk"]
conan-sdk = ["lock", "preload", "conan-sdk"]
ninja-build = ["lock", "preload", "ninja-build"]
curl-build = ["lock", "preload", "curl-build"]
kill-demo = ["lock", "preload", "kill-demo"]
ruby-sdk = ["lock", "preload", "ruby-sdk"]
qemu-arm-build = ["lock", "preload", "qemu-arm-build"]
shell-test = ["lock", "preload", "shell-test"]
workflows-test = ["preload", "workflows-test"]
