# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Create release
  release:
    permissions:
      contents: write
    runs-on: macos-latest
    steps:
      - uses: facebook/install-dotslash@latest
      - name: Checkout
        run: git clone --filter=blob:none https://github.com/work-spaces/workflows
        shell: bash
      - name: Update path
        run: echo "$PWD/workflows/bin" >> $GITHUB_PATH
        shell: bash
      - name: spaces check version
        run: spaces --version
        shell: bash
      - name: spaces create workspace
        run: spaces create --name=spaces-deploy --config=workflows/spaces_deploy.toml
        shell: bash
      - name: spaces release
        run: cd spaces-deploy && spaces run-action --name=release
        shell: bash
        env:
           GH_TOKEN: ${{ github.token }}
  build:
    permissions:
      contents: write
    needs: release
    runs-on: macos-latest
    strategy:
        matrix:
            os:
                - windows-latest
    steps:
      - uses: facebook/install-dotslash@latest
      - name: Checkout
        run: git clone --filter=blob:none https://github.com/work-spaces/workflows
        shell: bash
      - name: Update path
        run: echo "$PWD/workflows/bin" >> $GITHUB_PATH
        shell: bash
      - name: spaces check version
        run: spaces --version
        shell: bash
      - name: spaces create workspace
        run: spaces create --name=spaces-deploy --config=workflows/spaces_deploy.toml
        shell: bash
      - name: spaces deploy
        run: cd spaces-deploy && spaces run-action --name=deploy
        shell: bash
        env:
           GH_TOKEN: ${{ github.token }}



      

